<div align="center"> <h3><font color='cyan'>CSE 574 Section D: Introduction to Machine Learning, Fall 2023 </font> 
<h1> Assignment 0 - Python Introduction

<h3>Checkpoint: September 7, Thu, 11:59pm
<h2><font color='red'>Final Due Date: </font> September 14, Thu, 11:59pm</div>

Welcome to your first CSE 574 assignment! The goal of this assignment is to sharpen your programming skills needed for this class. It is focused on familiarizing yourself with Python and main data science libraries that will be used for other assignments as well.

There are a total of six parts. We will focus on basic Python functions, explore numpy, pandas, matplotlib, scikit-learn libraries,  and analyze the real-world dataset.

If you are new to Python, check our [Python resources page](https://ubuffalo-my.sharepoint.com/:w:/g/personal/avereshc_buffalo_edu/EZoQjG_dJpNJgOPmzjIVtCQBdMUeNL9llFbOSQyFYidk7w?e=Tds2E3) and our Recitation 0 & 1.


### Submission

All the details you need for this assignment are located within this notebook. You are expected to follow every block and complete the task within the marks ``` # BEGIN_YOUR_CODE ``` and ```# END_YOUR_CODE```. Do not modify or edit code beyond these lines. You can add helper functions in the new cells, if needed. We recommend completing the task within this .ipynb notebook, if needed you can convert it and submit as .py script. Try to make your code as clean and simple as possible and be sure to write your answers between the begin answer and end answer comments.

1. Submit at **Brighspace > Assesments > Assignments**
2. The code of your implementations should be written in Python
3. All project files should be submitted as jupyter notebooks named UBIT_assignment0_checkpoint.ipynb or UBIT_assignment0_final.ipynb, e.g. avereshc_assignment0_checkpoint.ipynb or avereshc_assignment0_final.ipynb.
4. Please submit a .ipynb file only. Submitions with .py, .json, .pdf or any other type won't be considered for evaluation. Your Jupyter notebook should be saved with the results.  
5. Include all the references that have been used to complete the assignment.

### Checkpoint Submission <font color='red'>[Due Date: Sep 7]</font>
Complete Part 1, Part 2, Part 3 and submit the code in the .ipynb file named UBIT_assignment0_checkpoint.ipynb. Checkpoint will be evaluated after the final submission.

### Final Submission <font color='red'>[Due Date: Sep 14]</font>
Complete all parts of the assignment and submit the code in the .ipynb file named UBIT_assignment0_final.ipynb. You may add slight modification to your Checkpoint submission if needed.

**Assignment Outline**

| Part | Description | # of tasks | Points |
| --- | --- | --- | --- |
| [Part 1](#part1) | Python & Numpy Basics | 21 | 25 |
| [Part 2](#part2) | Algorithms | 2 | 10 |
| [Part 3](#part3) | Pandas Basics | 9 | 15 |
| [Part 4](#part4) | Matplotlib Basics | 8 | 20 |
| [Part 5](#part5) | Scikit Learn Basics | 3 | 20 |
| [Part 6](#part6) | Optuna Basics | 2 | 10 |
| [References](#references) | Include all the references used |

    
### Academic Integrity

This task must be completed individually.
The standing policy of the Department is that all students involved in any academic integrity violation (e.g. plagiarism in any way, shape, or form) will receive an F grade for the course. The catalog describes plagiarism as “Copying or receiving material from any source and submitting that material as one’s own, without acknowledging and citing the particular debts to the source, or in any other manner representing the work of another as one’s own.”. Refer to the [Office of Academic Integrity](https://www.buffalo.edu/academic-integrity.html) for more details.


### Late Days Policy
You can use up to 7 late days throughout the course toward any programming taks, assignments' checkpoint or final submission. You do not have to inform the instructor, as the late submission will be tracked in UBlearns.

### FAQ
>What does 'raise Exception("Not implemented yet")' mean?

Here we define a custom exception to highlight that the task is not implemented yet. Once you implement your code, ensure to remove this part.

>Can I add code beyond # BEGIN_YOUR_CODE parts.

Yes, you can add helper functions. Add them in the separate cell with the comments, why you need it

<a id='part1'></a>
## Part 1: Python and Numpy Basics [20 Points]

The first part of this assignment gives you practice with python syntax. Follow the cells below for the instructions.

In [1]:
''' 1. Hello UB
Write a function that will print a phrase "Hello UB! " 101 times

Expected Output: "Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! ........"
'''

# BEGIN_YOUR_CODE
def greet():
    print(101*"Hello UB! ")
    
greet()
# END_YOUR_CODE

Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! Hello UB! 

In [106]:
''' 2. Adding elements to a list during the runtime
Create an empty list and add five of your favourite holiday destinations to the list during the runtime using functions input() and append()
Print out the list.
'''

# BEGIN_YOUR_CODE
spots=[]
for spot in range(5):
    spots.append(input())
spots
# END_YOUR_CODE

['TX', 'DA', 'FL', 'CA', 'NY']

In [107]:
''' 3. Updating elements
Given a string my_list, update the third element(i.e. 'ten') to 10 and sixth element(i.e. 'twenty five') to 25, so the output is as follows: [0, 5, 10, 15, 20, 25]
Print out the updated list.

Expected Output: [0, 5, 10, 15, 20, 25]
'''

my_list = [0, 5, 'ten', 15, 20, 'twenty five']

# BEGIN_YOUR_CODE
my_list[2],my_list[5]=[10,25]
my_list
# END_YOUR_CODE

[0, 5, 10, 15, 20, 25]

In [108]:
''' 4. Counting occurrences 
Write a function that counts the number of times a given word appears in a sentence. 
The word should be matched as a whole word, and the search should be case-insensitive.
For example: "The book is on the table", total occurances of "the" is 2.
'''

sentence = "The cat and the dog played in the park next to the theater. The cat was happy."
word_to_count = "the"

# BEGIN_YOUR_CODE
def ocscount(sen,word):
    words = list(map(str.lower,sen.split(' ')))
    return words.count(word)
ocscount(sentence,word_to_count)
# END_YOUR_CODE

5

In [109]:
''' 5. Pattern
Create a function that generates and prints a specific number pattern based on the input integer n. 
The pattern consists of rows where each row contains consecutive multiples of the row number.

Example Output:

For 'n = 3', the pattern will be:
1
2 4
3 6 9

For 'n = 6', the pattern will be:
1
2 4
3 6 9
4 8 12 16
5 10 15 20 25
6 12 18 24 30 36

Only submissions with a written function that will encode this exact pattern will be considered for evaluation
'''

# BEGIN_YOUR_CODE

def printpat(n):
    for row in range(1,n+1):
        for col in range(1,row+1):
            print(row*col,end=' ')
        print()

printpat(4)
printpat(6)

# END_YOUR_CODE

1 
2 4 
3 6 9 
4 8 12 16 
1 
2 4 
3 6 9 
4 8 12 16 
5 10 15 20 25 
6 12 18 24 30 36 


In [110]:
''' 6. Reversing
Reverse the order of elements in a list given below, so the expected output is as follows: ['Avengers', 'Age of Ultron', 'Infinity War', 'Endgame']
Print the reversed list.

'''

list1 = ["Endgame", "Infinity War", "Age of Ultron", "Avengers"]

# BEGIN_YOUR_CODE
list1 = list1[::-1]

list1
# END_YOUR_CODE

['Avengers', 'Age of Ultron', 'Infinity War', 'Endgame']

In [111]:
''' 7. Numbering a list
Write a function that will return a numbered list of the famous actors whose name starts from 'C' using "enumerate()" function.
Print the numbered list

Expected output:
1. Christian Bale
2. Chris Evans
3. Chris Hemsworth
4. Cate Blanchett

'''

actors = ['Margot Robbie', 'Christian Bale', 'Ryan Gosling', 'Chris Evans', 'Chris Hemsworth', 'Cate Blanchett']

# BEGIN_YOUR_CODE

def enum(numlist):
    return list(enumerate(list(filter(lambda s:s.startswith('C'),numlist)),start=1))

numlist = enum(actors)

numlist
    

# END_YOUR_CODE

[(1, 'Christian Bale'),
 (2, 'Chris Evans'),
 (3, 'Chris Hemsworth'),
 (4, 'Cate Blanchett')]

In [112]:
''' 8. Combining lists
Combine two lists given below using zip() function and print out the result
Print the combined list

'''

actors = ['Robert Downey Jr.', 'Scarlett Johansson', 'Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo']
role = ['Iron Man', 'Black Widow', 'Captain America', 'Thor', 'Hulk']

# BEGIN_YOUR_CODE
list(zip(actors,role))
# END_YOUR_CODE

[('Robert Downey Jr.', 'Iron Man'),
 ('Scarlett Johansson', 'Black Widow'),
 ('Chris Evans', 'Captain America'),
 ('Chris Hemsworth', 'Thor'),
 ('Mark Ruffalo', 'Hulk')]

In [113]:
''' 9. Sum function
Modify the given function to compute and return the sum of two integer values a and b
'''

def add(a: int, b: int) -> int:

    # BEGIN_YOUR_CODE

    return a+b

    # END_YOUR_CODE

We defined ```add_test``` to test your ```add``` function. For this function we ```import random``` library. This is a very commonly used package that helps to generate random values. For example:

``` python
random.randint(0, 100) #Returns any random integer in range [0, 100]
```

In [114]:
import random

def add_test():
    a = random.randint(0, 9)
    b = random.randint(0, 9)
    result = add(a, b)

    return('Value of a is {0}, value of b is {1}, and their sum is {2}.'.format(a, b,result))

In [115]:
# Here we call our function 'add_test' to test your add function with random values
if __name__ == '__main__':
   print(add_test())

Value of a is 5, value of b is 5, and their sum is 10.


In this section we will explore one of the most commonly used package - Numpy. You can refer to the [Official NumPy Guide](https://numpy.org/doc/stable/).

In [116]:
''' 10. Import the numpy package
'''

# BEGIN_YOUR_CODE

import numpy as np

# END_YOUR_CODE

In [117]:
''' 11. Random integers
Create a function that uses the NumPy library to generate an array of 10 random integers. 
The integers should be in the range [0, 50], both inclusive.
Print the results.

Example Output:
[0 25 41 14  3  2 49 36  9 42]

'''

# BEGIN_YOUR_CODE
arr = np.random.randint(1,51,size=(10,))
arr
# END_YOUR_CODE

array([ 7, 32, 40, 33, 18, 32, 40, 13, 23,  9])

In [118]:
''' 12. Slicing
Slice the above array and extract the first 2 elements, the last two elements, and all elements that are left in the middle.
'''

# BEGIN_YOUR_CODE
first_two = arr[:2]
last_two = arr[2:-2]
middle = arr[-2:]
# END_YOUR_CODE

print('The first 2 elements are {0} \nThe last two elements are {1} \nElements in the middle are {2}.'.format(first_two, last_two, middle))

The first 2 elements are [ 7 32] 
The last two elements are [40 33 18 32 40 13] 
Elements in the middle are [23  9].


In [119]:
''' 13. Split an array
For the above list 'array' split the list into 5 equal parts and print it
Output format will be as follows : [array([1,2]), array([3,4]), array([5,6]), array([7,8]), array([9,10])]
Use built-in function from NumPy to split array
'''

# BEGIN_YOUR_CODE
arr = np.split(arr,5)

arr
# END_YOUR_CODE

[array([ 7, 32]),
 array([40, 33]),
 array([18, 32]),
 array([40, 13]),
 array([23,  9])]

In [120]:
''' 14. Arrays
a. Generate two arrays, 'array_a' and 'array_b', each containing 10 randomly selected integers from the range [1, 20] (both inclusive).
b. Print both arrays
b. Use a built-in NumPy function to find the unique elements in 'array_a' and store them in the variable 'unique_elements'.
c. Use a built-in NumPy function to find the common elements shared by 'array_a' and 'array_b' and store them in the variable 'common_elements'.
d. Print 'unique_elements' and 'common_elements'
'''

# BEGIN_YOUR_CODE
A = np.random.randint(1,21,size=(10,))
B = np.random.randint(1,21,size=(10,))

print("A:",A)
print("B:",B)

unique_elements = np.unique(A)
common_elements = np.intersect1d(A,B)

print(unique_elements)
print(common_elements)

# END_YOUR_CODE

A: [ 9 13  1  1 17 16 11  4 20  3]
B: [14 18 11 16  8 16 17  5 20 18]
[ 1  3  4  9 11 13 16 17 20]
[11 16 17 20]


In [121]:
''' 15. Array operations
You have two arrays, array1 and array2, both containing 5 integer values. Perform the following operations using NumPy functions:
a. Calculate the element-wise sum of array1 and array2.
b. Calculate the element-wise difference between array1 and array2.
c. Calculate the element-wise product of array1 and a scalar value of 3.
d. Calculate the mean (average) value of elements in array2.
e. Calculate the maximum value in array1.


Provide the resulting arrays and values after each operation.

Expected output:
Element-wise sum: [15 30 45 60 75]
Element-wise difference: [ 5 10 15 20 25]
Element-wise product with scalar: [ 30  60  90 120 150]
Mean of array2: 15.0
Maximum value in array1: 50
'''

array1 = np.array([10, 20, 30, 40, 50])
array2 = np.array([5, 10, 15, 20, 25])

# BEGIN_YOUR_CODE

print("Element-wise sum:",np.add.reduce([array1,array2]))
print("Element-wise difference:",np.subtract.reduce([array1,array2]))
print("Element-wise product with scalar:",array1*3)
print("Mean of array2:",np.mean(array2))
print("Maximum value in array1:",np.max(array1))

# END_YOUR_CODE

Element-wise sum: [15 30 45 60 75]
Element-wise difference: [ 5 10 15 20 25]
Element-wise product with scalar: [ 30  60  90 120 150]
Mean of array2: 15.0
Maximum value in array1: 50


In [122]:
''' 16. Changing dimensions
Combine your 1D arrays defined above to a 2D matrix and print its shape. The final output dimension should be 2x5.
'''

# BEGIN_YOUR_CODE

com_array = np.array([array1,array2])

com_array.shape

# END_YOUR_CODE

(2, 5)

In [123]:
''' 17. Changing dimensions
Convert a matrix below to 1D array and print its dimension
'''

A = np.array([[3,4], [5,6], [7,8]])

# BEGIN_YOUR_CODE

A = A.flatten()

A.shape

# END_YOUR_CODE

(6,)

In [161]:
''' 18. Matrices
a. Create two matrices A and B of size 4X6 and 6X4 respectively with random values in range [0 , 1), 0 is inclusive and 1 is exclusive
b. Perform the dot product of matrices A and B
c. Print matrix A, matrix B, and their dot product
'''

# BEGIN_YOUR_CODE
A = np.random.rand(4, 6)
B = np.random.rand(6, 4)
dot_product = np.dot(A,B)
# END_YOUR_CODE

print('\nMatrix A is \n{0} \nMatrix B is \n{1}, \nTheir product is \n{2}'.format(A, B, dot_product))


Matrix A is 
[[0.58147721 0.89807218 0.46362826 0.7629679  0.31097649 0.35019013]
 [0.70751289 0.43115727 0.73864257 0.59973587 0.91446574 0.47565474]
 [0.96283765 0.79298135 0.68315785 0.35578513 0.65183709 0.64871872]
 [0.02822273 0.35721895 0.69622639 0.80653097 0.26987755 0.15006822]] 
Matrix B is 
[[0.40472522 0.88712577 0.86835329 0.48950889]
 [0.99198172 0.82983366 0.0330896  0.07667863]
 [0.43728534 0.06445391 0.64965136 0.72329974]
 [0.97967384 0.86524892 0.05900236 0.58214956]
 [0.18427073 0.48863538 0.96422222 0.20961763]
 [0.89961338 0.09736089 0.30582851 0.45137781]], 
Their product is 
[[2.44874681 2.13718269 1.2878067  1.35625905]
 [2.22100619 2.04512143 2.17110092 1.6691785 ]
 [2.52730651 2.2457461  2.15404175 1.66282415]
 [1.64509792 1.21067647 0.84233625 1.13861691]]


In [130]:
''' 19. Matrix scalar multiplication
a. Multiply the previously defined matrix A by a scalar value of 5 using the multiply() function.
b. Print a modified matrix A
'''

# BEGIN_YOUR_CODE
A = A*5

A
# END_YOUR_CODE

array([[250, 185,  65, 155,  45, 120],
       [ 80, 235, 195,  40,  45, 100],
       [190,  75, 230,   5, 140, 110],
       [ 95, 150,  40, 225,  90, 125]])

In [131]:
''' 20. Maximum value
a. Use the np.max() function to find the maximum value in each row of matrix A from Question 18.
b. Store the resulting maximum values in the variable 'max_values'.
c. Print out the results

Expected output:
max_values = [row1_max row2_max row3_max row4_max row5_max]
'''

# BEGIN_YOUR_CODE

max_values = [np.max(i) for i in A]

max_values

# END_YOUR_CODE

[250, 235, 230, 225]

In [159]:
''' 21. Element-wise multiplication
Define two matrices A (3X4) and B (3X4) with random integer values in range [0, 9], both inclusive. Perform element-wise multiplication of Matrices A and B
'''

# BEGIN_YOUR_CODE
A = np.random.randint(0, 10, size=(3, 4))
B = np.random.randint(0, 10, size=(3, 4))
multiplication = A*B
# END_YOUR_CODE

print('\nMatrix A is \n{0} \nMatrix B is \n{1}, \nTheir element-wise multiplication is \n{2}'.format(A, B, multiplication))


Matrix A is 
[[6 7 7 9]
 [6 2 3 9]
 [0 7 6 5]] 
Matrix B is 
[[6 0 6 2]
 [4 5 9 1]
 [1 9 2 2]], 
Their element-wise multiplication is 
[[36  0 42 18]
 [24 10 27  9]
 [ 0 63 12 10]]


<a id='part2'></a>
## Part 2 - Algorithms [10 Points]

### Euclidian Distance

Let point $p$ have Cartesian coordinates $(p_1,p_2)$ and let point $q$ have coordinates $(q_1,q_2)$. Then the distance between $p$ and $q$ is given by:
    $d(p,q) = \sqrt{(q_1-p_1)^2 + (q_2-p_2)^2}$.</math>

In [28]:
''' 1. Euclidean distance
Using numpy library return the Euclidean distance between two locations, where the locations are pairs of numbers (e.g., (3, 5)) '''

import math as m
import random

def euclidean_distance(loc1: tuple[int], loc2: tuple[int]) -> float:

    # BEGIN_YOUR_CODE

    return m.sqrt((loc2[0]-loc1[0])**2+(loc2[1]-loc1[1])**2)

    # END_YOUR_CODE

In [29]:
def euclidean_distance_test():
    random.seed(42)
    for _ in range(10):
        x1 = random.randint(0, 10)
        x2 = random.randint(0, 10)
        y1 = random.randint(0, 10)
        y2 = random.randint(0, 10)
        dist = euclidean_distance((x1, x2), (y1, y2))
    return('Loc1 is ({0}, {1}), loc2 is ({2}, {3}). Euclidian disctance is {4}.'.format(x1, x2, y1, y2, dist))

In [30]:
if __name__ == '__main__':
    print(euclidean_distance_test())

Loc1 is (3, 5), loc2 is (1, 1). Euclidian disctance is 4.47213595499958.


### String Operations

In [22]:
''' 2. Alphabetically first word
Given a string, lowercase all the elements, then sort our all words in the alphabetical order and return the word that comes first, lexicographically.
If the input text is an empty string, return an empty string or throw an error. '''

def first_word(text: str) -> str:

    # BEGIN_YOUR_CODE

    if not text:
        return ''
    
    return sorted(list(map(str.lower,text.split(' '))))[0]

    # END_YOUR_CODE

In [23]:
''' The output for following test cases will be as follows 'to', 'class', 'decisions', 'cat'
'''

def first_word_test():
    result0 = first_word('WelCome tO Ub')
    result1 = first_word('CSE574 IntRo to ML cLasS')
    result2 = first_word('SequenCes of DeCiSions')
    result3 = first_word('Wolf, Panther, Leopard, Dog, Cat')
    return result0, result1, result2, result3

In [24]:
if __name__ == '__main__':
    print(first_word_test())

('to', 'class', 'decisions', 'cat')


## Load from Drive*

*If you are using Goolge Colab, uncomment the following piece of code and verify the file using the command, if you can see your file ```penguins.csv``` you are good to go.

In [ ]:
# !pwd
# !ls

In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')
#%cd ..
#%cd /content/drive/MyDrive

<a id='part3'></a>
##  Part 3 - Pandas Basics [20 Points]

Some important resources:

- [A Pandas guide](https://pandasguide.readthedocs.io/en/latest/) covers fundamental information about the package

- [Pandas Cheat Sheet](https://www.datacamp.com/community/blog/python-pandas-cheat-sheet)

### Penguin dataset
In this section we will explore with you Palmer Archipelago (Antarctica) penguin dataset. It contains three penguin species and includes measurements of bill length, bill depth, flipper length and body mass. Overall, we are provided with 344 data samples.
![image.png](attachment:image.png)

The dataset consists of 7 columns:
- species: penguin species (Chinstrap, Adélie, or Gentoo)
- culmen_length_mm: culmen length (mm)
- culmen_depth_mm: culmen depth (mm)
- flipper_length_mm: flipper length (mm)
- body_mass_g: body mass (g)
- island: island name (Dream, Torgersen, or Biscoe) in the Palmer Archipelago (Antarctica)
- gender: penguin gender (female, male)

#### What are culmen length & depth?
The culmen is "the upper ridge of a bird's beak"

[Culmen length & depth Image](https://allisonhorst.github.io/palmerpenguins/reference/figures/culmen_depth.png)


#### What are flippers?
Penguins wings are called flippers. They are flat, thin, and broad with a long, tapered shape and a blunt, rounded tip.

[Penguins Body Parts Image](https://ubuffalo-my.sharepoint.com/:i:/g/personal/avereshc_buffalo_edu/EXuO-kSq4j9Pg7BUwq5WkycBDkRx3Ku_h76OmhjbDBA1dw?e=P0lIFc)


In [2]:
''' 1. Install and import pandas library
'''

# BEGIN_YOUR_CODE

!pip install pandas

import pandas as pd

# END_YOUR_CODE


[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [158]:
''' 2. Reading data
Read the dataset and extract it into a DataFrame using the Pandas library.
'''

# BEGIN_YOUR_CODE

df = pd.read_csv('penguins.csv')
df,type(df)

# END_YOUR_CODE

(       species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
 0       Adelie  Torgersen            39.1           18.7              181.0   
 1       Adelie  Torgersen            39.5           17.4              186.0   
 2       Adelie  Torgersen            40.3           18.0              195.0   
 3       Adelie  Torgersen             NaN            NaN                NaN   
 4       Adelie  Torgersen            36.7           19.3              193.0   
 ..         ...        ...             ...            ...                ...   
 339  Chinstrap      Dream            55.8           19.8              207.0   
 340  Chinstrap      Dream            43.5           18.1              202.0   
 341  Chinstrap      Dream            49.6           18.2              193.0   
 342  Chinstrap      Dream            50.8           19.0              210.0   
 343  Chinstrap      Dream            50.2           18.7              198.0   
 
      body_mass_g  gender  year  
 0  

In [4]:
''' 3. Basic Statistics 
Provide the main statistics about the entries in the dataset, including mean, standard deviation, and other relevant statistics.
'''

# BEGIN_YOUR_CODE

df.describe()

# END_YOUR_CODE

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
count      342.000000     342.000000         342.000000   342.000000   
mean        43.921930      17.151170         200.915205  4201.754386   
std          5.459584       1.974793          14.061714   801.954536   
min         32.100000      13.100000         172.000000  2700.000000   
25%         39.225000      15.600000         190.000000  3550.000000   
50%         44.450000      17.300000         197.000000  4050.000000   
75%         48.500000      18.700000         213.000000  4750.000000   
max         59.600000      21.500000         231.000000  6300.000000   

              year  
count   344.000000  
mean   2008.029070  
std       0.818356  
min    2007.000000  
25%    2007.000000  
50%    2008.000000  
75%    2009.000000  
max    2009.000000

In [5]:
''' 4. Dataset overview
Print top 15 rows of the dataset'''

# BEGIN_YOUR_CODE

df.head(15)

# END_YOUR_CODE

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0   Adelie  Torgersen            39.1           18.7              181.0   
1   Adelie  Torgersen            39.5           17.4              186.0   
2   Adelie  Torgersen            40.3           18.0              195.0   
3   Adelie  Torgersen             NaN            NaN                NaN   
4   Adelie  Torgersen            36.7           19.3              193.0   
5   Adelie  Torgersen            39.3           20.6              190.0   
6   Adelie  Torgersen            38.9           17.8              181.0   
7   Adelie  Torgersen            39.2           19.6              195.0   
8   Adelie  Torgersen            34.1           18.1              193.0   
9   Adelie  Torgersen            42.0           20.2              190.0   
10  Adelie  Torgersen            37.8           17.1              186.0   
11  Adelie  Torgersen            37.8           17.3              180.0   
12  Adelie  Torgersen            41.1           17.6              182.0   
13  Adelie  Torgersen            38.6           21.2              191.0   
14  Adelie  Torgersen            34.6           21.1              198.0   

    body_mass_g  gender  year  
0        3750.0    male  2007  
1        3800.0  female  2007  
2        3250.0  female  2007  
3           NaN     NaN  2007  
4        3450.0  female  2007  
5        3650.0    male  2007  
6        3625.0  female  2007  
7        4675.0    male  2007  
8        3475.0     NaN  2007  
9        4250.0     NaN  2007  
10       3300.0     NaN  2007  
11       3700.0     NaN  2007  
12       3200.0  female  2007  
13       3800.0    male  2007  
14       4400.0    male  2007

In [7]:
''' 5. Shape
Print shape of the dataset '''

# BEGIN_YOUR_CODE

df.shape

# END_YOUR_CODE

(344, 8)

In [16]:
''' 6. Columns
Identify and return all the unique column names'''

# BEGIN_YOUR_CODE

list(df.columns)

# END_YOUR_CODE

['species',
 'island',
 'bill_length_mm',
 'bill_depth_mm',
 'flipper_length_mm',
 'body_mass_g',
 'gender',
 'year']

In [15]:
''' 7. Penguin species
Print a list of penguin species used in the dateset'''

# BEGIN_YOUR_CODE

list(df['species'].unique())

# END_YOUR_CODE

['Adelie', 'Gentoo', 'Chinstrap']

In [149]:
''' 8. String to categorical
Convert one of the features with string datatype to categorical (e.g. species, island, gender).
This can be done by assigning a unique numerical value to each unique string value in each categorical feature

https://pandas.pydata.org/docs/user_guide/categorical.html

Example:
species = ['setosa', 'versicolor', 'setosa', 'virginica', 'versicolor']
species_categorical = [0, 1, 0, 2, 1]
'''

# BEGIN_YOUR_CODE
categories={'Adelie':0, 'Gentoo':1, 'Chinstrap':2}

df['species_categorical'] =  df['species'].map(categories).astype("category")

df[['species','species_categorical']]

# END_YOUR_CODE

species species_categorical
0       Adelie                   0
1       Adelie                   0
2       Adelie                   0
3       Adelie                   0
4       Adelie                   0
..         ...                 ...
339  Chinstrap                   2
340  Chinstrap                   2
341  Chinstrap                   2
342  Chinstrap                   2
343  Chinstrap                   2

[344 rows x 2 columns]

In [157]:
''' 9. Feature normalization
Normalize one of the non-categorical features.
   a. Select a column that you want to normalize (e.g. culmen_length_mm, culmen_depth_mm, flipper_length_mm, body_mass_g)
   b. Find the min and max values for accross the selected column
   c. Rescale the selected column to the range from 0 to 1 using the formula (x - min) / (max - min), where x is the original value
   d. Store the normalized values and print the results

Why do we do this? Normalization is to transform features to be on a similar scale. This improves the performance and training stability of the model.
Note: normalize() function is not allowed as it is a part of scikit-learn library
'''

# BEGIN_YOUR_CODE

bmassmin,bmassmax=np.min(df['body_mass_g']),np.max(df['body_mass_g'])

df['norm_body_mass_g']=df['body_mass_g'].map(lambda x:(x-bmassmin)/(bmassmax-bmassmin))

df[['body_mass_g','norm_body_mass_g']].dropna()

# END_YOUR_CODE

body_mass_g  norm_body_mass_g
0         3750.0          0.291667
1         3800.0          0.305556
2         3250.0          0.152778
4         3450.0          0.208333
5         3650.0          0.263889
..           ...               ...
339       4000.0          0.361111
340       3400.0          0.194444
341       3775.0          0.298611
342       4100.0          0.388889
343       3775.0          0.298611

[342 rows x 2 columns]

<a id='part4'></a>
## Part 4: Matplotlib Basics [20 Points]

Heatmaps is a useful plot tool which help us visualize the data density or distribution. Refer the below documentation for more details on heatmap.

[Matplotlib tutorial](https://machinelearningknowledge.ai/matplotlib-heatmap-complete-tutorial-for-beginners/)

**Note:** You can only use matplotlib library for the following tasks

In [ ]:
''' 1. Install and import matplotlib library
'''

# BEGIN_YOUR_CODE

# END_YOUR_CODE

In [ ]:
''' 2. Creating and visualizing a heatmap
Randomly generated 2D array to create and visualize a heatmap using Matplotlib.
You can refer to: https://matplotlib.org/stable/gallery/images_contours_and_fields/image_annotated_heatmap.html
a. Generate a random 2D array with dimensions 12x15 using any function, e.g. np.random.rand(), np.random.uniform(), np.random.randint()
b. Create the heatmap using plt.imshow() and pass the random array as the data
c. Customize the plot by adding a colorbar using plt.colorbar() and providing a descriptive title using plt.title()
d. Display the heatmap using plt.show()
'''

# BEGIN YOUR CODE

# END YOUR CODE

In [ ]:
''' 3. Plotting a function
Explore list comprehension and visualization by plotting the function y = 1/x, for a given range of x values. 
List comprehension is a powerful technique that allows you to create lists in a concise and efficient way.
You can check https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions to learn how to use list comprehension
a. Given the range of x values from 1 to 25, both inclusive, use list comprehension to calculate the corresponding y values for y = 1/x
b. Create the plot using plt.plot() by passing the calculated x and y values as arguments
c. Improve the plot by providing a title, labeling the x-axis and y-axis using plt.title(), plt.xlabel(), and plt.ylabel()
d. Add a grid to the plot for better readability using plt.grid()
e. Display the plot using plt.show()

'''

x = range(1,26)

# BEGIN YOUR CODE

# END YOUR CODE

In [ ]:
''' 4. Plotting a function using lambda function
For the given value x plot the function y = x^3 using lambda function y.

Lambda function is a small anonymous function which consist of a single expression, and is usually used when we need the function for a smaller duration
https://realpython.com/python-lambda/

a. Given the range of x values from 0 to 24, use a lambda function to calculate the corresponding y values based on the function y = x^3
b. Create the plot using plt.plot() with the calculated x and y values
c. Customize the plot by adding a title, x-axis label, y-axis label, and grid using plt.title(), plt.xlabel(), plt.ylabel(), and plt.grid().
d. Display the plot
'''

x = range(25)

# BEGIN YOUR CODE

# END YOUR CODE


In [ ]:
''' 5. Plotting multiple functions on one graph
Plot a graph with two lines representing the functions y = x^3 and y = x^4 for the provided range of x values.

a. Given the range of x values from 0 to 24, use a lambda function to calculate the corresponding y values for y = x^3 (you can use your code from above)
b. For the function y = x^4, calculate the y values using either list comprehension or a lambda function.
c. Create the line plot for y = x^3 using plt.plot() and the scatter plot for y = x^4 using plt.scatter().
d. Customize the plot by adding a title, x-axis label, y-axis label, legend, and grid using appropriate functions such as plt.title(), plt.xlabel(), plt.ylabel(), plt.legend(), and plt.grid().
e. Display the plot using plt.show()

Note: you can check more at https://matplotlib.org/stable/tutorials/introductory/pyplot.html
'''

x = range(25)

# BEGIN YOUR CODE

# END YOUR CODE

In [ ]:
'''6. Creating subplots

Create subplots to display the graphs of the tangent (tan) and cotangent (cot) functions side by side. The value of 
theta will range from -60 to 60 degrees.

a. Generate an array of theta values using np.linspace() or np.arange() to cover the range from -60 to 60 degrees.
b. Calculate the corresponding y values for both the tangent (tan) and cotangent (cot) functions using np.tan() and 1 / np.tan()
c. Create subplots using plt.subplots() and arrange them side by side
d. Plot the tangent and cotangent functions in their respective subplots using plt.plot()
e. Customize each subplot with titles and labels for x-axis and y-axis using plt.title(), plt.xlabel(), and plt.ylabel()
f. Display the subplots using plt.show()
'''

# BEGIN YOUR CODE

# END YOUR CODE

In [ ]:
''' 7. Plotting total number of penguins per species
Use Penguin ("penguin.csv") dataset uploaded above to plot the total number of penguins per species
a. Group the data by the "species" column and calculate the total number of penguins for each species using groupby() and count()
b. Create a bar graph using plt.bar() to display the total number of penguins per species
c. Customize the graph by adding a title, x-axis label, y-axis label, rotating x-axis labels for better readability
d. Display the plot
'''

# BEGIN YOUR CODE

# END YOUR CODE

In [ ]:
''' 8. Plotting total number of penguins in body mass range
Display a graph displaying the total number of penguins in the specified body mass range.
a. Filter the data to include only the penguins with body mass (body_mass_g) in the range of (3200, 4500], 3200 - exclusive and 4500-inclusive
b. Group the filtered data by body mass range using the 'pd.cut()' function with specified bins as follows: 3200-3500, 3500-3800, 3800-4100, 4100-4400, and 4400-4500. After applying 'pd.cut()', use the 'groupby()' function to group the data based on these body mass ranges.
c. Create a bar graph using plt.bar() to display the total number of penguins in the specified body mass range
d. Customize the graph by adding a title, x-axis label, y-axis label, rotating x-axis labels for better readability
e. Display the plot
'''

# BEGIN YOUR CODE

# END YOUR CODE

#### Results analyzing

Analyze the graph and answer the following two questions:

**1) What is your inference from the above graph?**

*YOUR ANSWER:*

**2) What is the distribution of penguins across different body mass ranges within the specified range(3200, 4500]?**

*YOUR ANSWER:*

**3) Which is the most common species of penguins?**

*YOUR ANSWER:*


<a id='part5'></a>
# Part 5: Sckit-learn Basics [20 Points]

Skit-learn is a commonly used data analysis library. It contains in-build unsupervised and supervised learning algorithms. Check more details here - https://scikit-learn.org/stable/.
In this part we will use scikit-learn library

In [ ]:
''' 1. Install and import scikit-learn library
'''

# BEGIN_YOUR_CODE

# END_YOUR_CODE

In [ ]:
''' 2. Prepare Penguins dataset for training
a. Define our X_data = all the columns, exept 'Species'. You can use drop() function
b. Define Y_target = 'Species' column from the dataset
c. Use the train_test_split() function to split the dataset into training and testing sets. Pass the features (X_data) and target (Y_target), set test_size to 0.2 for an 80/20 split
d. Print the shapes of X_train, X_test, Y_train, and Y_test sets
'''

# BEGIN_YOUR_CODE

# END_YOUR_CODE

In [ ]:
''' 3. Fit the model
a. Create and fit a logistic regression model to predict the 'Species' of a penguin using all of the other features in the dataset.
b. You can use one hot encoding to encode categorical-based feature ('island' and 'gender') or reuse your code from abouve
c. Create a logistic regression model using LogisticRegression()
d. Fit the model using the training data
e. Make predictions on the testing data using the trained model
f. Print the accuracy score by comparing the predicted values with the actual target values using accuracy_score()
g. Print the parameter values of the logistic regression model using get_params()

You can read more about the inbuild Logistic Regression model here - https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
'''

# BEGIN_YOUR_CODE
    
# END_YOUR_CODE

<a id='part6'></a>
# Part 6: Optuna Basics [10 Points]

Optuna is a an open-source framework that helps to automatically search best hyperparameters, when training machine learning or deep learning models. 
Check more details here - https://optuna.org/ . In this part we will use optuna framework.

In [ ]:
''' 1. Install and import optuna
You can read more about installation here - https://optuna.org/#installation
'''

# BEGIN_YOUR_CODE

# END_YOUR_CODE

You can refer code examples on how to use optuna here - https://optuna.org/#code_examples

In [ ]:
''' 2. Optimize hyperparameters using Optuna
a. Reuse the code from Part 5 for fitting a logistic regression model using scikit-learn
b. Use Optuna to determine the optimal values for two hyperparameters in logistic regression: C and max_iter
    The aim is to find the hyperparameters that result in the highest accuracy score
    The hyperparameter C should be in the range [0.01, 10], and max_iter should be within the range of [100, 1000]
c. Print the optimal values of C and max_iter and corresponding accuracy score obtained
'''

# BEGIN_YOUR_CODE

# END_YOUR_CODE

<a id='references'></a>
## References Used

**List below all the references you used to complete this assignment, including full links to the online resources**

<font color='red'>Missing references will result in -5 points for the assignmnent. If you haven't used any resources to complete this assignments, just add "None" below</font>

In [ ]:
https://numpy.org/doc/stable/reference/arrays.html
https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html
https://pandas.pydata.org/docs/user_guide/categorical.html
https://docs.python.org/3/library/random.html?highlight=random#module-random


**Instructions**:

*   Do not copy paste code from the references. You can refer to better understand and then code yourself.
*   Prefer official documentations over other sources, for accurate and standard practices.
*   Do not use ChatGPT. This assignment is aiming to strengthen your Python skills. Python is a crucial language in AI and data science, so ensure you're comfortable with its various aspects.
*   Have fun and all the best!

P.S. Start early and post on piazza, if you have any questions!



